# Generated by Django 5.0.2 on 2024-02-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipimodel',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/recipi_pic'),
        ),
    ]
